### ISSUE TITLE
Cannot run program "youtube-dl" (in directory "/Users/main/workspace/Gary"): error=2, No such file or directory

### ISSUE THREAD

**Issue by yeSpud** [sapher/youtubedl-java#3]
Heres the current code I have, & according to the example, it should work:
```
String videoUrl = url;
		String directory = System.getProperty("user.dir");

		YoutubeDLRequest request = new YoutubeDLRequest(videoUrl, directory);

		request.setOption("no-mark-watched");
		request.setOption("no-playlist");
		request.setOption("extract-audio");
		request.setOption("audio-format \"mp3\"");
		request.setOption("output \"a.%(ext)s\"");

		YoutubeDLResponse response = YoutubeDL.execute(request);

		String stdOut = response.getOut();

		System.out.println(stdOut);
```
However, when running, I get the error: `Cannot run program "youtube-dl" (in directory "/Users/main/workspace/Gary"): error=2, No such file or directory`

From what I can tell, the directory is valid, as thats where the java application is running from, so I don't know why it thinks its invalid

**Comment by yeSpud** [comment]
Figured it out, turns out I wasnt the first to post this issue

**Comment by sapher** [comment]
I think I'm going to implement a more explicit way to tell the user that the executable is not found 👍  I hope you have find a way to get your code working
