### ISSUE TITLE
File format

### ISSUE THREAD

**Issue by yeSpud** [sapher/youtubedl-java#4]
Im trying to download the audio as an `mp3`, but I keep getting the error:
```
com.sapher.youtubedl.YoutubeDLException: ERROR: ffprobe or avprobe not found. Please install one.

	at com.sapher.youtubedl.YoutubeDL.execute(YoutubeDL.java:90)
	at TestingFunctions.main(TestingFunctions.java:37)
```

I do have ffmpeg installed, so I don't know whats the issue

Heres what I have in terms of code:

```java
File a = new File("a.mp3");
		File b = new File("a.webm");
		if (a.exists()) {
			a.delete();
		}
		if (b.exists()) {
			b.delete();
		}

		String videoUrl = "https://www.youtube.com/watch?v=BrCKvKXvN2c";
		String directory = System.getProperty("user.dir");

		try {
			YoutubeDLRequest request = new YoutubeDLRequest(videoUrl, directory);
			YoutubeDL.setExecutablePath("/usr/local/Cellar/youtube-dl/2017.09.15/bin/youtube-dl");
			request.setOption("no-mark-watched");
			request.setOption("no-playlist");
			request.setOption("extract-audio");
			request.setOption("audio-format mp3");
			request.setOption("output a.%(ext)s");
			
			
			
			System.out.println("Downloading...");
			YoutubeDLResponse response = YoutubeDL.execute(request);

			String stdOut = response.getOut();
			
			System.out.println(stdOut);

		} catch (Exception YoutubeDLException) {
			YoutubeDLException.printStackTrace();
		}
```

**Comment by sapher** [comment]
Yes you need to have ffmpeg or avconv to be installed. Youtube-dl need this to do conversion. You are on macOS, to install ffmpeg you can do `brew install ffmpeg`

**Comment by yeSpud** [comment]
ffmpeg is installed, yet when I run it, it still gives me the error.

**Comment by yeSpud** [comment]
Could it be that I have to specify the file path like I did for `YoutubeDL.setExecutablePath()` ?

**Comment by sapher** [comment]
If ffmpeg is installed you should be able to invoke it through the terminal by doing `ffmpeg` like so
<img width="470" alt="capture d ecran 2017-10-05 a 20 18 50" src="https://user-images.githubusercontent.com/1940597/31238267-846ddb12-aa0a-11e7-8eb7-c6fcee3ac618.png">

You can add `request.setOption("prefer-ffmpeg");` or `request.setOption("prefer-avconv");` to force the use of one or another. 

Also you can use `request.setOption("ffmpeg-location /my_path/PATH");` to manually set the path of ffmpeg executable. I don't think you have to do that. If you have `youtube-dl`, `ffmpeg` or `avconv` in your *PATH* it should work with no issue.

As this library seemed to be use by some people, I'm going to rethink the API.

**Comment by yeSpud** [comment]
Ok, that seemed to work. Thanks!
